CREATE DATABASE quizmachine;

CREATE TABLE player (
id SERIAL PRIMARY KEY,
name VARCHAR(3) NOT NULL UNIQUE
);

CREATE TABLE game (
  id SERIAL PRIMARY KEY,
  score INT NOT NULL,
  questions INT NOT NULL,
  player_id INT NOT NULL,
  FOREIGN KEY (player_id) REFERENCES player (id)
);

INSERT INTO player VALUES (1, 'JOE');
INSERT INTO player VALUES (2, 'BEN');
ALTER SEQUENCE player_id_seq RESTART WITH 3 INCREMENT BY 1;

INSERT INTO game VALUES (1, 15, 8, 1);
INSERT INTO game VALUES (2, 25, 10, 1);
INSERT INTO game VALUES (3, 18, 7, 2);
ALTER SEQUENCE game_id_seq RESTART WITH 4 INCREMENT BY 1;